# Haskell Platform 2013.2.0.0
# GHC: 7.6.3

before_install:
  # ==============================
  #  Prepare Haskell environment
  # ==============================
  #
  # install Haskell Platform from Ubuntu repositories
  - sudo apt-get update -qq
  - sudo apt-get --yes --force-yes -qq install haskell-platform

  # ====================================
  #  This should be done for each build
  # ====================================

  # show GHC and Cabal versions
  - ghc --version
  - cabal --version

  # update Cabal database
  - cabal update

# install project dependencies
install:
  - cabal install --only-dependencies --enable-tests

# configure, build and run tests
script:
  - cabal configure --enable-tests && cabal build && cabal test
