# Haskell Platform 2014.2.0.0
# GHC: 7.8.3

# download and install generic Linux binaries
before_install:
  - sudo wget -O /haskell-platform.tar.gz https://www.haskell.org/platform/download/2014.2.0.0/haskell-platform-2014.2.0.0-unknown-linux-x86_64.tar.gz
  - cd / && sudo tar xvf haskell-platform.tar.gz
  - sudo /usr/local/haskell/ghc-7.8.3-x86_64/bin/activate-hs

  # show GHC and Cabal versions
  - ghc --version
  - cabal --version

  # update Cabal database
  - cabal update

# install project dependencies
install:
  - cabal install --only-dependencies --enable-tests

# configure, build and run tests
script:
  - cabal configure --enable-tests && cabal build && cabal test
